import {
  arbitrum,
  arbitrumSepolia,
  avalanche,
  avalancheFuji,
  base,
  baseSepolia,
  bsc,
  bscTestnet,
  gnosis,
  gnosisChiado,
  linea,
  lineaSepolia,
  mainnet,
  opBNB,
  opBNBTestnet,
  optimism,
  optimismSepolia,
  polygon,
  polygonAmoy,
  polygonZkEvm,
  polygonZkEvmTestnet,
  scroll,
  scrollSepolia,
  sei,
  seiTestnet,
  sepolia,
  sonic,
  sonicTestnet,
  unichain,
  unichainSepolia,
  worldchain,
  worldchainSepolia,
  zksync,
  zksyncSepoliaTestnet,
} from 'viem/chains';

/**
 * Chains used for bridging (LI.FI + CCTP).
 * @see https://docs.li.fi/widget/wallet-management#keep-chains-in-sync
 * @see https://developers.circle.com/cctp/concepts/supported-chains-and-domains
 */
export const BRIDGE_CHAINS = [
  // Mainnet
  mainnet,
  bsc,
  arbitrum,
  base,
  avalanche,
  polygon,
  polygonZkEvm,
  scroll,
  opBNB,
  linea,
  zksync,
  gnosis,
  optimism,
  sei,
  sonic,
  unichain,
  worldchain,
  // Testnet
  sepolia,
  bscTestnet,
  arbitrumSepolia,
  baseSepolia,
  avalancheFuji,
  polygonAmoy,
  polygonZkEvmTestnet,
  scrollSepolia,
  opBNBTestnet,
  lineaSepolia,
  zksyncSepoliaTestnet,
  gnosisChiado,
  optimismSepolia,
  seiTestnet,
  sonicTestnet,
  unichainSepolia,
  worldchainSepolia,
] as const;
