import { NLP_PRODUCT_ID, QUOTE_PRODUCT_ID } from '@nadohq/client';
import { COMMON_ALT_SEARCH_TERMS } from '../commonAltSearchTerms';
import { KNOWN_PRODUCT_IDS } from '../knownProductIds';
import { MARKET_DESCRIPTIONS } from '../marketDescriptions';
import { NLP_TOKEN_INFO } from '../nlpTokenInfo';
import { PRIMARY_QUOTE_SYMBOLS } from '../primaryQuoteSymbols';
import { SpotProductMetadata } from '../types';
import {
  KBTC_INK,
  KBTC_INK_SEPOLIA,
  NLP_INK,
  NLP_INK_SEPOLIA,
  USDC_INK,
  USDC_INK_SEPOLIA,
  USDT0_INK,
  USDT0_INK_SEPOLIA,
  WAAPLX_INK,
  WAAPLX_INK_SEPOLIA,
  WAMZNX_INK,
  WAMZNX_INK_SEPOLIA,
  WETH_INK,
  WETH_INK_SEPOLIA,
  WGOOGLX_INK,
  WGOOGLX_INK_SEPOLIA,
  WMETAX_INK,
  WMETAX_INK_SEPOLIA,
  WMSFTX_INK,
  WMSFTX_INK_SEPOLIA,
  WNVDAX_INK,
  WNVDAX_INK_SEPOLIA,
  WQQQX_INK,
  WQQQX_INK_SEPOLIA,
  WSPYX_INK,
  WSPYX_INK_SEPOLIA,
  WTSLAX_INK,
  WTSLAX_INK_SEPOLIA,
  XAUT0_INK_SEPOLIA,
} from './tokens';

/**
 * Ink Testnet
 */

export const INK_TESTNET_SPOT_METADATA_BY_PRODUCT_ID: Record<
  number,
  SpotProductMetadata
> = {
  [QUOTE_PRODUCT_ID]: {
    token: USDT0_INK_SEPOLIA,
    marketName: '',
    fullMarketName: 'USDT0',
    marketDescription: MARKET_DESCRIPTIONS.usdt0,
    altSearchTerms: [],
    quoteProductId: QUOTE_PRODUCT_ID,
    marketCategories: new Set(['crypto']),
  },
  1: {
    token: KBTC_INK_SEPOLIA,
    marketName: `kBTC/${PRIMARY_QUOTE_SYMBOLS.usdt0}`,
    fullMarketName: 'Kraken Wrapped Bitcoin',
    marketDescription: MARKET_DESCRIPTIONS.kbtc,
    altSearchTerms: COMMON_ALT_SEARCH_TERMS.kbtc,
    quoteProductId: QUOTE_PRODUCT_ID,
    marketCategories: new Set(['crypto']),
  },
  [KNOWN_PRODUCT_IDS.weth]: {
    token: WETH_INK_SEPOLIA,
    marketName: `wETH/${PRIMARY_QUOTE_SYMBOLS.usdt0}`,
    fullMarketName: 'Wrapped Ether',
    marketDescription: MARKET_DESCRIPTIONS.weth,
    altSearchTerms: COMMON_ALT_SEARCH_TERMS.weth,
    quoteProductId: QUOTE_PRODUCT_ID,
    marketCategories: new Set(['crypto']),
  },
  5: {
    token: USDC_INK_SEPOLIA,
    marketName: `USDC/${PRIMARY_QUOTE_SYMBOLS.usdt0}`,
    fullMarketName: 'USD Coin',
    marketDescription: MARKET_DESCRIPTIONS.usdc,
    altSearchTerms: COMMON_ALT_SEARCH_TERMS.usdc,
    quoteProductId: QUOTE_PRODUCT_ID,
    marketCategories: new Set(['crypto']),
  },
  [NLP_PRODUCT_ID]: {
    token: NLP_INK_SEPOLIA,
    marketName: NLP_TOKEN_INFO.symbol,
    fullMarketName: 'Nado Liquidity Provider',
    marketDescription: MARKET_DESCRIPTIONS.nlp,
    altSearchTerms: COMMON_ALT_SEARCH_TERMS.nlp,
    quoteProductId: QUOTE_PRODUCT_ID,
    marketCategories: new Set(['crypto']),
  },
  115: {
    token: WQQQX_INK_SEPOLIA,
    marketName: `QQQx/${PRIMARY_QUOTE_SYMBOLS.usdt0}`,
    fullMarketName: 'Invesco QQQ',
    marketDescription: MARKET_DESCRIPTIONS.qqqx,
    altSearchTerms: COMMON_ALT_SEARCH_TERMS.qqqx,
    quoteProductId: QUOTE_PRODUCT_ID,
    marketCategories: new Set(['stocks']),
  },
  117: {
    token: WSPYX_INK_SEPOLIA,
    marketName: `SPYx/${PRIMARY_QUOTE_SYMBOLS.usdt0}`,
    fullMarketName: 'SPDR S&P 500 ETF',
    marketDescription: MARKET_DESCRIPTIONS.spyx,
    altSearchTerms: COMMON_ALT_SEARCH_TERMS.spyx,
    quoteProductId: QUOTE_PRODUCT_ID,
    marketCategories: new Set(['stocks']),
  },
  143: {
    token: WAAPLX_INK_SEPOLIA,
    marketName: `AAPLx/${PRIMARY_QUOTE_SYMBOLS.usdt0}`,
    fullMarketName: 'Apple',
    marketDescription: MARKET_DESCRIPTIONS.aaplx,
    altSearchTerms: COMMON_ALT_SEARCH_TERMS.aaplx,
    quoteProductId: QUOTE_PRODUCT_ID,
    marketCategories: new Set(['stocks']),
  },
  145: {
    token: WAMZNX_INK_SEPOLIA,
    marketName: `AMZNx/${PRIMARY_QUOTE_SYMBOLS.usdt0}`,
    fullMarketName: 'Amazon',
    marketDescription: MARKET_DESCRIPTIONS.amznx,
    altSearchTerms: COMMON_ALT_SEARCH_TERMS.amznx,
    quoteProductId: QUOTE_PRODUCT_ID,
    marketCategories: new Set(['stocks']),
  },
  147: {
    token: WGOOGLX_INK_SEPOLIA,
    marketName: `GOOGLx/${PRIMARY_QUOTE_SYMBOLS.usdt0}`,
    fullMarketName: 'Alphabet',
    marketDescription: MARKET_DESCRIPTIONS.googlx,
    altSearchTerms: COMMON_ALT_SEARCH_TERMS.googlx,
    quoteProductId: QUOTE_PRODUCT_ID,
    marketCategories: new Set(['stocks']),
  },
  149: {
    token: WMETAX_INK_SEPOLIA,
    marketName: `METAx/${PRIMARY_QUOTE_SYMBOLS.usdt0}`,
    fullMarketName: 'Meta Platforms',
    marketDescription: MARKET_DESCRIPTIONS.metax,
    altSearchTerms: COMMON_ALT_SEARCH_TERMS.metax,
    quoteProductId: QUOTE_PRODUCT_ID,
    marketCategories: new Set(['stocks']),
  },
  151: {
    token: WMSFTX_INK_SEPOLIA,
    marketName: `MSFTx/${PRIMARY_QUOTE_SYMBOLS.usdt0}`,
    fullMarketName: 'Microsoft',
    marketDescription: MARKET_DESCRIPTIONS.msftx,
    altSearchTerms: COMMON_ALT_SEARCH_TERMS.msftx,
    quoteProductId: QUOTE_PRODUCT_ID,
    marketCategories: new Set(['stocks']),
  },
  153: {
    token: WNVDAX_INK_SEPOLIA,
    marketName: `NVDAx/${PRIMARY_QUOTE_SYMBOLS.usdt0}`,
    fullMarketName: 'NVIDIA',
    marketDescription: MARKET_DESCRIPTIONS.nvdax,
    altSearchTerms: COMMON_ALT_SEARCH_TERMS.nvdax,
    quoteProductId: QUOTE_PRODUCT_ID,
    marketCategories: new Set(['stocks']),
  },
  155: {
    token: WTSLAX_INK_SEPOLIA,
    marketName: `TSLAx/${PRIMARY_QUOTE_SYMBOLS.usdt0}`,
    fullMarketName: 'Tesla',
    marketDescription: MARKET_DESCRIPTIONS.tslax,
    altSearchTerms: COMMON_ALT_SEARCH_TERMS.tslax,
    quoteProductId: QUOTE_PRODUCT_ID,
    marketCategories: new Set(['stocks']),
  },
  159: {
    token: XAUT0_INK_SEPOLIA,
    marketName: `XAUT0/${PRIMARY_QUOTE_SYMBOLS.usdt0}`,
    fullMarketName: 'Tether Gold',
    marketDescription: MARKET_DESCRIPTIONS.xaut0,
    altSearchTerms: COMMON_ALT_SEARCH_TERMS.xaut0,
    quoteProductId: QUOTE_PRODUCT_ID,
    marketCategories: new Set(['commodities']),
  },
};

/**
 * Ink
 */

export const INK_SPOT_METADATA_BY_PRODUCT_ID: Record<
  number,
  SpotProductMetadata
> = {
  [QUOTE_PRODUCT_ID]: {
    token: USDT0_INK,
    marketName: '',
    fullMarketName: 'USDT0',
    marketDescription: MARKET_DESCRIPTIONS.usdt0,
    altSearchTerms: [],
    quoteProductId: QUOTE_PRODUCT_ID,
    marketCategories: new Set(['crypto']),
  },
  1: {
    token: KBTC_INK,
    marketName: `kBTC/${PRIMARY_QUOTE_SYMBOLS.usdt0}`,
    fullMarketName: 'Kraken Wrapped Bitcoin',
    marketDescription: MARKET_DESCRIPTIONS.kbtc,
    altSearchTerms: COMMON_ALT_SEARCH_TERMS.kbtc,
    quoteProductId: QUOTE_PRODUCT_ID,
    marketCategories: new Set(['crypto']),
  },
  [KNOWN_PRODUCT_IDS.weth]: {
    token: WETH_INK,
    marketName: `wETH/${PRIMARY_QUOTE_SYMBOLS.usdt0}`,
    fullMarketName: 'Wrapped Ether',
    marketDescription: MARKET_DESCRIPTIONS.weth,
    altSearchTerms: COMMON_ALT_SEARCH_TERMS.weth,
    quoteProductId: QUOTE_PRODUCT_ID,
    marketCategories: new Set(['crypto']),
  },
  5: {
    token: USDC_INK,
    marketName: `USDC/${PRIMARY_QUOTE_SYMBOLS.usdt0}`,
    fullMarketName: 'USD Coin',
    marketDescription: MARKET_DESCRIPTIONS.usdc,
    altSearchTerms: COMMON_ALT_SEARCH_TERMS.usdc,
    quoteProductId: QUOTE_PRODUCT_ID,
    marketCategories: new Set(['crypto']),
  },
  [NLP_PRODUCT_ID]: {
    token: NLP_INK,
    marketName: NLP_TOKEN_INFO.symbol,
    fullMarketName: 'Nado Liquidity Provider',
    marketDescription: MARKET_DESCRIPTIONS.nlp,
    altSearchTerms: COMMON_ALT_SEARCH_TERMS.nlp,
    quoteProductId: QUOTE_PRODUCT_ID,
    marketCategories: new Set(['crypto']),
  },
  115: {
    token: WQQQX_INK,
    marketName: `QQQx/${PRIMARY_QUOTE_SYMBOLS.usdt0}`,
    fullMarketName: 'Invesco QQQ',
    marketDescription: MARKET_DESCRIPTIONS.qqqx,
    altSearchTerms: COMMON_ALT_SEARCH_TERMS.qqqx,
    quoteProductId: QUOTE_PRODUCT_ID,
    marketCategories: new Set(['stocks']),
  },
  117: {
    token: WSPYX_INK,
    marketName: `SPYx/${PRIMARY_QUOTE_SYMBOLS.usdt0}`,
    fullMarketName: 'SPDR S&P 500 ETF',
    marketDescription: MARKET_DESCRIPTIONS.spyx,
    altSearchTerms: COMMON_ALT_SEARCH_TERMS.spyx,
    quoteProductId: QUOTE_PRODUCT_ID,
    marketCategories: new Set(['stocks']),
  },
  143: {
    token: WAAPLX_INK,
    marketName: `AAPLx/${PRIMARY_QUOTE_SYMBOLS.usdt0}`,
    fullMarketName: 'Apple',
    marketDescription: MARKET_DESCRIPTIONS.aaplx,
    altSearchTerms: COMMON_ALT_SEARCH_TERMS.aaplx,
    quoteProductId: QUOTE_PRODUCT_ID,
    marketCategories: new Set(['stocks']),
  },
  145: {
    token: WAMZNX_INK,
    marketName: `AMZNx/${PRIMARY_QUOTE_SYMBOLS.usdt0}`,
    fullMarketName: 'Amazon',
    marketDescription: MARKET_DESCRIPTIONS.amznx,
    altSearchTerms: COMMON_ALT_SEARCH_TERMS.amznx,
    quoteProductId: QUOTE_PRODUCT_ID,
    marketCategories: new Set(['stocks']),
  },
  147: {
    token: WGOOGLX_INK,
    marketName: `GOOGLx/${PRIMARY_QUOTE_SYMBOLS.usdt0}`,
    fullMarketName: 'Alphabet',
    marketDescription: MARKET_DESCRIPTIONS.googlx,
    altSearchTerms: COMMON_ALT_SEARCH_TERMS.googlx,
    quoteProductId: QUOTE_PRODUCT_ID,
    marketCategories: new Set(['stocks']),
  },
  149: {
    token: WMETAX_INK,
    marketName: `METAx/${PRIMARY_QUOTE_SYMBOLS.usdt0}`,
    fullMarketName: 'Meta',
    marketDescription: MARKET_DESCRIPTIONS.metax,
    altSearchTerms: COMMON_ALT_SEARCH_TERMS.metax,
    quoteProductId: QUOTE_PRODUCT_ID,
    marketCategories: new Set(['stocks']),
  },
  151: {
    token: WMSFTX_INK,
    marketName: `MSFTx/${PRIMARY_QUOTE_SYMBOLS.usdt0}`,
    fullMarketName: 'Microsoft',
    marketDescription: MARKET_DESCRIPTIONS.msftx,
    altSearchTerms: COMMON_ALT_SEARCH_TERMS.msftx,
    quoteProductId: QUOTE_PRODUCT_ID,
    marketCategories: new Set(['stocks']),
  },
  153: {
    token: WNVDAX_INK,
    marketName: `NVDAx/${PRIMARY_QUOTE_SYMBOLS.usdt0}`,
    fullMarketName: 'NVIDIA',
    marketDescription: MARKET_DESCRIPTIONS.nvdax,
    altSearchTerms: COMMON_ALT_SEARCH_TERMS.nvdax,
    quoteProductId: QUOTE_PRODUCT_ID,
    marketCategories: new Set(['stocks']),
  },
  155: {
    token: WTSLAX_INK,
    marketName: `TSLAx/${PRIMARY_QUOTE_SYMBOLS.usdt0}`,
    fullMarketName: 'Tesla',
    marketDescription: MARKET_DESCRIPTIONS.tslax,
    altSearchTerms: COMMON_ALT_SEARCH_TERMS.tslax,
    quoteProductId: QUOTE_PRODUCT_ID,
    marketCategories: new Set(['stocks']),
  },
};
