import { Fuul, UserIdentifierType } from '@fuul/sdk';
import { toBigNumber } from '@nadohq/client';
import { createQueryKey, useSubaccountContext } from '@nadohq/react-client';
import { useQuery } from '@tanstack/react-query';
import { BigNumber } from 'bignumber.js';
import { NOT_CONNECTED_ALT_QUERY_ADDRESS } from 'client/hooks/query/consts/notConnectedAltQueryAddress';
import { parseISO } from 'date-fns';

export function addressFuulReferralEarningsPerUserQueryKey(address?: string) {
  return createQueryKey('addressFuulReferralEarningsPerUser', address);
}

interface ReferredUserEarnings {
  address: string;
  /**
   * Total volume generated by this referred user in USDT. This is already decimal adjusted
   */
  referredVolumeUsdt: BigNumber;
  joinTimeMillis: number;
}

/**
 * Queries a mapping of LOWERCASED address -> volume + earnings data
 * Lowercasing is used for easier lookups
 */
export function useQueryAddressFuulReferralEarningsPerUser() {
  const {
    currentSubaccount: { address },
  } = useSubaccountContext();

  const addressForQuery = address ?? NOT_CONNECTED_ALT_QUERY_ADDRESS;

  return useQuery({
    queryKey: addressFuulReferralEarningsPerUserQueryKey(addressForQuery),
    queryFn: async (): Promise<Record<string, ReferredUserEarnings>> => {
      const response = await Fuul.getPayoutsByReferrer({
        user_identifier: addressForQuery,
        user_identifier_type: UserIdentifierType.EvmAddress,
      });

      const earningsByAddress: Record<string, ReferredUserEarnings> = {};
      response.forEach((userObject) => {
        // User object is a single mapping of address -> values
        Object.entries(userObject).forEach(([address, values]) => {
          earningsByAddress[address.toLowerCase()] = {
            address,
            referredVolumeUsdt: toBigNumber(values.volume),
            joinTimeMillis: parseISO(values.date_joined).getTime(),
          };
        });
      });

      return earningsByAddress;
    },
    refetchInterval: 10000,
  });
}
