export const COMMON_ALT_SEARCH_TERMS = {
  aapl: ['Apple'],
  aave: ['Aave'],
  amzn: ['Amazon'],
  aster: ['Aster'],
  avax: ['Avalanche'],
  bch: ['Bitcoin Cash'],
  bnb: ['Binance Coin'],
  bonk: ['Bonk'],
  btc: ['Bitcoin'],
  doge: ['Dogecoin'],
  ena: ['Ethena'],
  eth: ['Ethereum'],
  fartcoin: ['Fartcoin'],
  hype: ['Hyperliquid', 'Hype'],
  jup: ['Jupiter'],
  kbtc: ['Wrapped Bitcoin', 'Kraken'],
  kpepe: ['PEPE'],
  link: ['Chainlink'],
  lit: ['Lighter'],
  ltc: ['Litecoin'],
  mon: ['Monad'],
  meta: ['Facebook'],
  msft: ['Microsoft'],
  nlp: ['Nado LP'],
  nvda: ['Nvidia'],
  eurusd: ['Euro'],
  gbpusd: ['British Pound'],
  googl: ['Google', 'Alphabet'],
  oil: ['Crude Oil', 'WTI'],
  qqq: ['Nasdaq', 'Invesco'],
  ondo: ['Ondo Finance'],
  pengu: ['Pudgy Penguins'],
  pump: ['Pumpfun'],
  silver: ['Silver', 'XAG'],
  spy: ['S&P 500', 'SPDR'],
  usdjpy: ['Japanese Yen'],
  skr: ['Solana Mobile Seeker'],
  sol: ['Solana'],
  sui: ['Sui'],
  tao: ['Bittensor', 'Tao'],
  tsla: ['Tesla'],
  uni: ['Uniswap'],
  usdc: ['USD', 'Circle'],
  useless: ['Useless'],
  weth: ['Wrapped Ethereum'],
  wlfi: ['World Liberty Financial'],
  xaut: ['Tether Gold'],
  xmr: ['Monero'],
  xpl: ['Plasma'],
  xrp: ['Ripple'],
  zec: ['Zcash'],
  zro: ['LayerZero'],
};
