export const COMMON_ALT_SEARCH_TERMS = {
  aapl: ['Apple'],
  aaplx: ['Apple', 'Wrapped Backed Apple'],
  aave: ['Aave'],
  amd: ['Advanced Micro Devices'],
  amzn: ['Amazon'],
  amznx: ['Amazon', 'Wrapped Backed Amazon'],
  avgo: ['Broadcom'],
  aster: ['Aster'],
  avax: ['Avalanche'],
  bbx: ['BlackBerry'],
  bch: ['Bitcoin Cash'],
  chip: ['USDAI', 'Chip'],
  bnb: ['Binance Coin'],
  bonk: ['Bonk'],
  btc: ['Bitcoin'],
  dell: ['Dell Technologies'],
  doge: ['Dogecoin'],
  ena: ['Ethena'],
  eth: ['Ethereum'],
  fartcoin: ['Fartcoin'],
  hype: ['Hyperliquid', 'Hype'],
  intc: ['Intel'],
  jup: ['Jupiter'],
  kbtc: ['Wrapped Bitcoin', 'Kraken'],
  kpepe: ['PEPE'],
  link: ['Chainlink'],
  lit: ['Lighter'],
  ltc: ['Litecoin'],
  mon: ['Monad'],
  mrvl: ['Marvell Technology'],
  mu: ['Micron Technology'],
  mega: ['MegaETH'],
  meta: ['Facebook'],
  metax: ['Facebook', 'Meta', 'Wrapped Backed Meta'],
  msft: ['Microsoft'],
  msftx: ['Microsoft', 'Wrapped Backed Microsoft'],
  mstr: ['MicroStrategy', 'Strategy'],
  near: ['NEAR Protocol'],
  nlp: ['Nado LP'],
  nvda: ['Nvidia'],
  nvdax: ['Nvidia', 'Wrapped Backed NVIDIA'],
  eurusd: ['Euro'],
  gbpusd: ['British Pound'],
  googl: ['Google', 'Alphabet'],
  googlx: ['Google', 'Alphabet', 'Wrapped Backed Alphabet'],
  oil: ['Crude Oil', 'WTI'],
  qqq: ['Nasdaq', 'Invesco'],
  qqqx: ['Nasdaq', 'Invesco'],
  ondo: ['Ondo Finance'],
  peng: ['Penguin Solutions'],
  pengu: ['Pudgy Penguins'],
  pump: ['Pumpfun'],
  silver: ['Silver', 'XAG'],
  spy: ['S&P 500', 'SPDR'],
  spyx: ['S&P 500', 'SPDR'],
  usdjpy: ['Japanese Yen'],
  skr: ['Solana Mobile Seeker'],
  sky: ['MakerDAO', 'Maker'],
  sndk: ['SanDisk'],
  sol: ['Solana'],
  spcx: ['SpaceX'],
  sui: ['Sui'],
  tao: ['Bittensor', 'Tao'],
  gram: ['Ton', 'The Open Network', 'Telegram'],
  tsla: ['Tesla'],
  tslax: ['Tesla', 'Wrapped Backed Tesla'],
  uni: ['Uniswap'],
  usdc: ['USD', 'Circle'],
  useless: ['Useless'],
  vvv: ['Venice AI', 'Venice'],
  weth: ['Wrapped Ethereum'],
  wld: ['Worldcoin'],
  wlfi: ['World Liberty Financial'],
  xaut: ['Tether Gold'],
  xaut0: ['Tether Gold'],
  xmr: ['Monero'],
  xpl: ['Plasma'],
  xrp: ['Ripple'],
  zec: ['Zcash'],
  zhipu: ['Zhipu AI', 'Knowledge Atlas Tech'],
  zro: ['LayerZero'],
};
