/**
 * Human-readable market descriptions, keyed by the same lowercase symbol keys
 * as {@link COMMON_ALT_SEARCH_TERMS}, which is the source of truth for what each
 * market represents. Served from `/api/product-metadata` and rendered on market
 * detail surfaces (web + mobile).
 *
 * When writing or editing this copy, follow the rules in
 * `docs/playbooks/WRITE_MARKET_DESCRIPTIONS.md`.
 */
export const MARKET_DESCRIPTIONS = {
  aapl: 'Apple Inc. designs, manufactures, and sells consumer electronics, software, and services, including the iPhone, Mac, iPad, Apple Watch, and AirPods, plus AppleCare, iCloud, and the App Store. Founded in 1976 by Steve Jobs and Steve Wozniak, it is headquartered in Cupertino, California, and is among the most valuable companies in the world.',
  aaplx:
    'AAPLx is a tokenized Apple Inc. share, an xStocks asset issued by Backed Finance and collateralized 1:1 by shares held in regulated custody. It gives on-chain exposure to the Apple stock price, letting traders gain and manage that exposure directly through smart contracts without holding the underlying equity through a broker.',
  aave: 'Aave is a leading decentralized protocol for lending and borrowing crypto, where users supply assets into pools to earn yield or borrow against posted collateral at variable or stable rates. The AAVE token is used for governance and as a backstop for protocol security, letting holders vote on markets, risk parameters, and treasury decisions.',
  amd: 'Advanced Micro Devices, Inc. designs CPUs, GPUs, and adaptive processors for PCs, data centers, gaming consoles, and embedded systems, and has become a major supplier of chips for artificial-intelligence workloads. Founded in 1969 and headquartered in Santa Clara, California, it competes directly with Intel and NVIDIA across key markets.',
  amzn: 'Amazon.com, Inc. is a global technology company spanning e-commerce, cloud computing through Amazon Web Services, digital streaming, devices, and advertising. Founded by Jeff Bezos in 1994 and headquartered in Seattle, Washington, it is one of the largest companies in the world, with AWS a major driver of its overall profitability.',
  amznx:
    'AMZNx is a tokenized Amazon.com, Inc. share, an xStocks asset issued by Backed Finance and collateralized 1:1 by shares held in regulated custody. It gives on-chain exposure to the Amazon stock price, letting traders gain and manage that exposure directly through smart contracts without holding the underlying equity through a broker.',
  avgo: 'Broadcom Inc. designs and supplies a broad range of semiconductor and infrastructure-software products, including networking, broadband, wireless, and enterprise-storage chips, plus custom silicon for major cloud customers. Headquartered in Palo Alto, California, it is among the largest chipmakers and a key supplier for AI data centers.',
  aster:
    'Aster is the native token of a decentralized exchange for perpetual futures, offering leveraged on-chain trading across a range of markets. The token is used for fees, trading incentives, and governance across the platform, aligning active traders and liquidity providers with the long-term growth of the protocol.',
  avax: 'Avalanche is a layer-1 blockchain known for high throughput, fast finality, and a customizable subnet architecture that lets teams launch tailored networks with their own rules. Launched in 2020 by Ava Labs, AVAX is used to pay fees, stake for rewards, and secure the network, and it anchors a growing ecosystem of DeFi and enterprise apps.',
  bbx: 'BlackBerry Limited is a Canadian technology company focused on cybersecurity software and embedded systems, including its QNX operating system widely used in automotive and industrial devices. Once known for its smartphones, it shifted to enterprise software and secure connectivity, and is headquartered in Waterloo, Ontario.',
  bch: "Bitcoin Cash is a cryptocurrency that forked from Bitcoin in 2017 to enable larger blocks, higher transaction throughput, and lower fees for everyday use. It is designed to work as peer-to-peer electronic cash for routine payments, prioritizing on-chain scaling and low-cost transfers over Bitcoin's more conservative block-size approach.",
  bnb: 'BNB is the native token of the BNB Chain ecosystem, used to pay transaction fees, access services, and power a wide range of on-chain applications. Launched by Binance in 2017, it features periodic token burns that reduce its total supply over time, and it underpins one of the most active smart-contract ecosystems in crypto.',
  bonk: 'kBONK tracks 1,000 BONK, a Solana-based meme coin that was widely airdropped to the Solana community in late 2022 as the network was recovering. BONK became one of the most recognized community meme tokens in the Solana ecosystem, spreading across wallets, exchanges, and consumer apps and helping revive on-chain activity and sentiment.',
  btc: 'Bitcoin is the first and largest cryptocurrency, a decentralized digital currency secured by a proof-of-work blockchain and maintained by a global network of miners. Created in 2009 by the pseudonymous Satoshi Nakamoto, it has a fixed supply capped at 21 million coins and is widely held as a store of value and a hedge against inflation.',
  chip: 'CHIP is the governance and utility token of USD.AI, a decentralized protocol that finances AI infrastructure through GPU-backed loans and issues the USDai synthetic dollar. CHIP holders stake the token and vote on risk parameters and protocol decisions, sharing in the growth of a system that connects on-chain capital to real compute demand.',
  dell: 'Dell Technologies Inc. designs and sells PCs, laptops, servers, storage, and a broad portfolio of enterprise IT infrastructure and services, increasingly geared toward AI-optimized systems. Founded by Michael Dell in 1984 and headquartered in Round Rock, Texas, it is a leading global hardware provider to consumers and businesses alike.',
  doge: 'Dogecoin is a meme cryptocurrency launched in 2013 by Billy Markus and Jackson Palmer, based on the Shiba Inu "Doge" internet meme. Originally created as a lighthearted joke, it has grown into a widely traded asset popular for tipping and payments, buoyed by an active community and repeated waves of mainstream attention.',
  ena: 'Ethena is the governance token of the Ethena protocol, which issues USDe, a synthetic dollar backed by crypto collateral and delta-neutral hedging strategies that aim to hold its peg. ENA holders vote on protocol parameters and risk settings, steering how the system manages collateral, yield distribution, and its overall risk profile.',
  eth: 'Ethereum is the leading smart-contract platform and the second-largest cryptocurrency, powering DeFi, NFTs, stablecoins, and a vast range of Web3 applications. Launched in 2015 by Vitalik Buterin and others, it transitioned to proof-of-stake in 2022, sharply cutting energy use while enabling ETH holders to stake and help secure the network.',
  fartcoin:
    'Fartcoin is a Solana-based meme coin that gained traction through internet humor and the rise of AI-agent culture on-chain. It has no inherent utility and trades primarily on community attention, virality, and speculation, becoming a recognizable name among the wave of purely social, narrative-driven tokens that emerged in the Solana ecosystem.',
  hype: 'HYPE is the native token of Hyperliquid, a high-performance decentralized exchange for perpetual futures built on its own purpose-made layer-1 blockchain. It is used for trading fees, staking, and governance of the protocol, and it aligns the community around a platform known for fast execution, deep liquidity, and an on-chain order book.',
  intc: "Intel Corporation designs and manufactures semiconductors, including the x86 CPUs that power much of the world's PCs and servers, and is investing heavily to rebuild its foundry business. Founded in 1968 and based in Santa Clara, California, it remains one of the most storied names in the chip industry as it pushes into new processes.",
  jup: "Jupiter is the token of the leading decentralized exchange aggregator on Solana, which routes trades across many liquidity sources to find the best available prices for users. JUP is used for governance of the Jupiter ecosystem, giving holders a say over incentives, product direction, and the treasury of one of Solana's most-used protocols.",
  kbtc: "kBTC is Kraken Wrapped Bitcoin, an ERC-20 token redeemable 1:1 for Bitcoin held in custody by Kraken. It brings the value of Bitcoin onto Ethereum and other smart-contract networks for use across DeFi applications, letting holders lend, trade, and provide liquidity with BTC exposure while relying on Kraken's regulated custody and reserves.",
  kpepe:
    'kPEPE tracks 1,000 PEPE, an Ethereum-based meme coin launched in 2023 and inspired by the Pepe the Frog character. PEPE quickly became one of the most traded meme tokens after its launch, drawing enormous trading volume and a large, highly online community, and it stands as a defining example of the meme-coin cycles on Ethereum.',
  link: 'Chainlink is a decentralized oracle network that connects smart contracts with real-world data, off-chain computation, and cross-chain messaging. Node operators are paid in LINK to deliver tamper-resistant data feeds, and the network has become critical infrastructure for DeFi, powering price feeds and services across many blockchains.',
  lit: 'Lighter is the native token of Lighter, a decentralized exchange for perpetual futures that offers verifiable on-chain order matching and liquidations for greater transparency. The token supports trading fees, incentives, and governance, aligning traders and liquidity providers with a platform focused on fairness and provable execution.',
  ltc: 'Litecoin is a peer-to-peer cryptocurrency created in 2011 by Charlie Lee as a faster, lower-cost complement to Bitcoin, often described as its silver counterpart. It uses the Scrypt hashing algorithm and offers quicker block times for everyday transactions, and it remains one of the longest-running and most widely accepted cryptocurrencies.',
  mon: 'Monad is the native token of Monad, a high-performance layer-1 blockchain that uses parallel execution to raise throughput while remaining fully compatible with the Ethereum Virtual Machine (EVM). MON is used to pay fees and help secure the network, giving Ethereum developers a familiar environment with far greater speed and capacity.',
  mrvl: 'Marvell Technology, Inc. designs semiconductors for data infrastructure, including networking, storage, and custom silicon tailored for cloud and AI workloads. Headquartered in Santa Clara, California, it is a key supplier of the connectivity and accelerated-computing components that power large data centers and next-generation AI systems.',
  mu: 'Micron Technology, Inc. manufactures memory and storage products such as DRAM and NAND flash used across computing, mobile, automotive, and data-center systems. Founded in 1978 and headquartered in Boise, Idaho, it is one of the few large-scale memory makers in the world and a key beneficiary of rising demand from AI and cloud infrastructure.',
  mega: 'MEGA is the native token of MegaETH, a real-time, high-performance Ethereum layer-2 built for very low latency and high throughput to support demanding on-chain applications. The token is used to pay fees and support network operations, backing a platform that aims to make Ethereum feel as responsive as a traditional web application.',
  meta: 'Meta Platforms, Inc. operates Facebook, Instagram, WhatsApp, and Messenger, earning most of its revenue from advertising while investing heavily in artificial intelligence and the metaverse. Founded by Mark Zuckerberg in 2004 and based in Menlo Park, California, it reaches billions of users across its family of social apps worldwide.',
  metax:
    'METAx is a tokenized Meta Platforms, Inc. share, an xStocks asset issued by Backed Finance and collateralized 1:1 by shares held in regulated custody. It gives on-chain exposure to the Meta stock price, letting traders gain and manage that exposure directly through smart contracts without holding the underlying equity through a broker.',
  msft: 'Microsoft Corporation develops software, cloud services, and hardware, including Windows, Office, the Azure cloud platform, Xbox, and a growing suite of AI products. Founded by Bill Gates and Paul Allen in 1975 and headquartered in Redmond, Washington, it is one of the largest technology companies in the world across consumer and enterprise.',
  msftx:
    'MSFTx is a tokenized Microsoft Corporation share, an xStocks asset issued by Backed Finance and collateralized 1:1 by shares held in regulated custody. It gives on-chain exposure to the Microsoft stock price, letting traders gain and manage that exposure directly through smart contracts without holding the underlying equity through a broker.',
  mstr: 'Strategy, formerly MicroStrategy, is a US business-intelligence software company that has become best known as the largest corporate holder of Bitcoin, funding purchases through equity and debt issuance. Founded in 1989 by Michael Saylor and headquartered in Tysons Corner, Virginia, its stock trades closely with the price of Bitcoin.',
  near: 'NEAR Protocol is a layer-1 blockchain focused on usability and scalability through sharding, which splits the network so transactions can process in parallel as demand grows. It offers low fees, fast finality, and human-readable account names, and it aims to make on-chain applications approachable for mainstream developers and everyday users.',
  nlp: "NLP is the Nado Liquidity Provider token, representing a share of the protocol's liquidity pool that backs trading on the exchange. Holders earn a portion of the trading fees and yield the pool generates, gaining passive exposure to platform activity while providing the liquidity that lets traders open and close positions on Nado markets.",
  nvda: 'NVIDIA Corporation designs GPUs and accelerated-computing platforms that sit at the center of gaming, professional graphics, and artificial intelligence, making it a pivotal supplier for the AI boom. Founded by Jensen Huang and others in 1993 and based in Santa Clara, California, it is among the most valuable companies in the world.',
  nvdax:
    'NVDAx is a tokenized NVIDIA Corporation share, an xStocks asset issued by Backed Finance and collateralized 1:1 by shares held in regulated custody. It gives on-chain exposure to the NVIDIA stock price, letting traders gain and manage that exposure directly through smart contracts without holding the underlying equity through a broker.',
  eurusd:
    'EUR/USD is the exchange rate between the euro and the US dollar, the two largest reserve currencies in the world. It is by far the most heavily traded currency pair on the foreign-exchange market and a key global benchmark, closely watched as a gauge of relative economic strength and monetary policy between the eurozone and the United States.',
  gbpusd:
    'GBP/USD is the exchange rate between the British pound and the US dollar, one of the oldest and most actively traded currency pairs in the world. It is nicknamed "cable" after the transatlantic telegraph cable once used to transmit its quotes, and it remains a closely followed barometer of UK and US economic and policy conditions.',
  googl:
    'Alphabet Inc. is the parent company of Google, spanning search, advertising, YouTube, Android, Chrome, and Google Cloud, along with deep AI research through DeepMind. Founded by Larry Page and Sergey Brin in 1998 and based in Mountain View, California, it is one of the largest technology companies in the world by revenue and reach.',
  googlx:
    'GOOGLx is a tokenized Alphabet Inc. share, an xStocks asset issued by Backed Finance and collateralized 1:1 by shares held in regulated custody. It gives on-chain exposure to the Alphabet stock price, letting traders gain and manage that exposure directly through smart contracts without holding the underlying equity through a broker.',
  oil: 'WTI tracks West Texas Intermediate crude oil, the primary benchmark for US oil prices and a key reference for global energy markets. It is a light, sweet grade priced at the Cushing, Oklahoma delivery hub and is widely traded through futures and derivatives, closely followed as an indicator of supply, demand, and broader economic conditions.',
  qqq: 'QQQ is the Invesco QQQ Trust, one of the most heavily traded exchange-traded funds in the world, tracking the Nasdaq-100 Index of the 100 largest non-financial companies listed on the Nasdaq. It offers concentrated exposure to large-cap technology and growth stocks, making it a popular proxy for the performance of the tech sector.',
  qqqx: 'QQQx is a tokenized product providing on-chain exposure to the Nasdaq-100 Index through the Invesco QQQ Trust, which holds the 100 largest non-financial companies listed on the Nasdaq. It lets traders gain concentrated exposure to large-cap technology and growth stocks directly on-chain, without holding the underlying fund through a broker.',
  ondo: 'Ondo Finance is a protocol focused on tokenizing real-world assets such as US Treasuries and money-market funds, bringing institutional-grade yield on-chain in a compliant, accessible form. ONDO is used for governance of the protocol, giving holders a say over products, partnerships, and the direction of one of the leading RWA platforms.',
  peng: 'Penguin Solutions, Inc. provides full-stack AI and high-performance computing infrastructure, spanning compute, memory, networking, and software for enterprises, neocloud providers, and sovereign AI initiatives. Founded in 1988 and headquartered in Milpitas, California, it supplies systems that help customers deploy and scale AI workloads.',
  pengu:
    "PENGU is the token of the Pudgy Penguins ecosystem, a popular NFT collection and consumer brand spanning toys, media, and digital collectibles that has crossed from crypto into mainstream retail. The token ties the community together across the brand's products, aligning collectors and fans with the growth of one of the best-known NFT franchises.",
  pump: "PUMP is the token associated with Pump.fun, a Solana-based platform that lets anyone launch a meme coin permissionlessly in seconds with no coding required. The token ties into the platform's trading and launchpad activity, connecting holders to a service that became a defining hub for the meme-coin creation boom on Solana.",
  silver:
    'XAG tracks the spot price of silver, a precious metal valued both as a critical industrial input for electronics, solar cells, and manufacturing, and as a store of value and inflation hedge. Its price reflects a blend of industrial demand and investment flows, making it more volatile than gold and closely watched across commodity markets.',
  spy: 'SPY is the SPDR S&P 500 ETF Trust, one of the oldest and largest exchange-traded funds in the world, tracking the S&P 500 Index of 500 leading large-cap US companies across all sectors. It is among the most heavily traded securities on the market and is widely used as a core benchmark for the overall performance of US equities.',
  spyx: 'SPYx is a tokenized product providing on-chain exposure to the S&P 500 Index through the SPDR S&P 500 ETF Trust, which tracks 500 leading large-cap US companies across all sectors. It lets traders gain broad exposure to the US stock market directly on-chain, using one of the most widely followed equity benchmarks without holding the fund through a broker.',
  usdjpy:
    'USD/JPY is the exchange rate between the US dollar and the Japanese yen, one of the most actively traded currency pairs in global foreign-exchange markets. It is closely watched as a gauge of risk sentiment and Bank of Japan policy, and it often moves sharply in response to interest-rate differentials between the United States and Japan.',
  skr: 'Seeker is the native utility and governance token of Solana Mobile, the community-owned smartphone ecosystem built around the Solana blockchain and its flagship crypto-native handset. It powers rewards and access within the Solana Mobile platform, tying hardware owners and app users to an ecosystem built for on-chain, mobile-first activity.',
  sky: "Sky (formerly Maker) is the governance token of the Sky protocol, the decentralized system that issues the USDS stablecoin backed by a mix of on-chain and real-world collateral. Holders vote on collateral types, risk parameters, and other protocol decisions, steering one of DeFi's longest-running and most influential stablecoin systems.",
  sndk: 'SanDisk Corporation designs and produces flash-memory storage, including solid-state drives, memory cards, and USB drives for both consumer and enterprise use. Headquartered in Milpitas, California, it is a well-known name in storage, supplying products that hold data across phones, cameras, laptops, and data-center systems worldwide.',
  sol: 'Solana is a high-throughput, proof-of-stake layer-1 blockchain known for very low fees and fast finality, making it a hub for consumer and DeFi applications. Launched in 2020, it uses a proof-of-history mechanism to order transactions efficiently and hosts a large, active ecosystem spanning meme coins, NFTs, payments, and trading apps.',
  spcx: 'SPCX tracks the share price of SpaceX, the space-launch and satellite company behind the reusable Falcon rockets, the Starship program, and the Starlink internet network. Founded by Elon Musk in 2002, it went public on the Nasdaq in June 2026, giving investors listed exposure to one of the most closely watched private companies to date.',
  sui: 'Sui is a layer-1 blockchain built on the Move programming language and designed for high throughput and low-latency transactions suited to consumer-scale applications. Its object-centric data model enables parallel execution of independent transactions, targeting gaming, social, and payment apps that demand speed and a smooth user experience.',
  tao: 'Bittensor is the native token of a decentralized network that incentivizes the training and sharing of machine-learning models across specialized subnets. Participants earn TAO for contributing useful intelligence to the network, aligning miners, validators, and developers around an open marketplace for producing and consuming AI.',
  gram: 'Gram (formerly Toncoin) is the native coin of The Open Network (TON), a sharded layer-1 blockchain originally developed by Telegram for fast, scalable payments and apps. It is deeply integrated with the Telegram messaging platform, giving its huge user base access to on-chain payments, mini-apps, and services directly inside their chats.',
  tsla: 'Tesla, Inc. designs and manufactures electric vehicles, battery energy-storage systems, and solar products, alongside advanced driver-assistance and self-driving software. Founded in 2003 and led by Elon Musk, it is headquartered in Austin, Texas, and is one of the most valuable and closely followed automakers in the world.',
  tslax:
    'TSLAx is a tokenized Tesla, Inc. share, an xStocks asset issued by Backed Finance and collateralized 1:1 by shares held in regulated custody. It gives on-chain exposure to the Tesla stock price, letting traders gain and manage that exposure directly through smart contracts without holding the underlying equity through a broker.',
  uni: 'Uniswap is the governance token of Uniswap, a leading decentralized exchange on Ethereum that pioneered the automated market maker model for on-chain trading. UNI holders vote on protocol upgrades, fee settings, and treasury decisions, guiding one of the most widely used and influential DeFi protocols across the broader ecosystem.',
  usdc: 'USD Coin is a fully reserved stablecoin pegged 1:1 to the US dollar, issued by Circle and backed by cash and short-dated US Treasuries held in regulated accounts. It is one of the most widely used stablecoins for payments, trading, and DeFi, valued for its transparency, regular attestations, and deep integration across crypto markets.',
  usdt0:
    "USDT0 is an omnichain deployment of Tether's USD₮ stablecoin, pegged 1:1 to the US dollar and designed to move seamlessly between networks. It lets the same dollar-backed asset move natively across multiple blockchains without fragmenting liquidity, giving users a consistent stablecoin experience wherever they trade, pay, or provide liquidity.",
  useless:
    'Useless Coin is a Solana-based meme coin that proudly advertises no roadmap and no utility, held purely for the irony of its own name. Its value comes entirely from community participation, humor, and speculation, making it a self-aware example of the purely social, narrative-driven tokens that thrive within the Solana meme-coin ecosystem.',
  vvv: "VVV is the token of Venice AI, a privacy-focused platform offering uncensored access to open-source generative-AI models without storing user data or conversations. Staking VVV grants a proportional share of the platform's daily compute capacity, tying holders to a service built around private, permissionless access to powerful AI models.",
  weth: 'Wrapped Ether is an ERC-20 token that represents Ether 1:1, making ETH compatible with the many smart contracts and DeFi protocols that expect the ERC-20 standard. It can be redeemed for ETH at any time, and it is widely used across decentralized exchanges, lending markets, and liquidity pools that require a standardized token.',
  wld: 'Worldcoin is the token of the World project, which uses iris-based biometric verification to establish proof of personhood and distinguish real humans from bots online. It aims to build a global identity and financial network for the age of AI, with WLD distributed to verified users and intended to support inclusive, large-scale access.',
  wlfi: "WLFI is the governance token of World Liberty Financial, a US-based decentralized-finance platform offering access to stablecoin, lending, and other DeFi products. Holders vote on proposals that shape the protocol, its supported assets, and its direction, giving the community a formal role in guiding the platform's development over time.",
  xaut: 'Tether Gold is a token backed by physical gold, with each token representing one troy ounce held in reserve as an allocated London Good Delivery bar. It offers convenient on-chain exposure to the price of gold, letting holders trade, transfer, and hold a gold-backed asset digitally while retaining a claim on the underlying metal.',
  xaut0:
    'XAUT0 is an omnichain deployment of Tether Gold (XAUT), backed by physical gold with each token representing one troy ounce held in reserve as a London Good Delivery bar. It offers on-chain exposure to the price of gold and is designed to move natively across multiple blockchains, keeping the same gold-backed asset unified across networks.',
  xmr: 'Monero is a privacy-centric cryptocurrency that hides the sender, receiver, and amount of every transaction by default, unlike transparent chains where activity is public. It uses ring signatures, stealth addresses, and confidential transactions to protect users, and it is widely regarded as the leading privacy coin in the market.',
  xpl: 'XPL is the native token of Plasma, a layer-1 blockchain optimized specifically for stablecoin payments with fast, low-cost, high-volume transfers. The token is used to pay fees, stake for rewards, and help secure the network, backing an ecosystem designed to make moving digital dollars cheap and near-instant for both users and businesses.',
  xrp: 'XRP is the native asset of the XRP Ledger, designed for fast, low-cost cross-border payments and settlement between financial institutions. Created by Ripple in 2012, it uses a consensus protocol instead of energy-intensive mining and settles transactions in seconds, positioning itself as infrastructure for global value transfer and remittances.',
  zec: "Zcash is a privacy-focused cryptocurrency that uses zero-knowledge proofs to enable optional shielded transactions, keeping the sender, receiver, and amount confidential. Users can choose between transparent and shielded addresses, and the technology allows a transaction's validity to be verified without revealing its underlying details.",
  zhipu:
    'Zhipu AI is a Chinese artificial-intelligence company that develops large language models, including its GLM series, along with enterprise AI applications. Spun out of research at Tsinghua University, it is among the leading AI startups in China, building foundation models and tools that compete with major domestic and global developers.',
  zro: 'LayerZero is the token of an omnichain interoperability protocol that lets applications and assets pass messages securely across many different blockchains. ZRO is used for governance and to help pay for cross-chain messaging, anchoring infrastructure that developers rely on to build multi-chain applications and move value across networks.',
};
